### ISSUE TITLE
Bypass YT Sanctions

### ISSUE THREAD

**Issue by Friedjof** [DvorakDwarf/Infinite-Storage-Glitch#39] opened 2023-02-23 12:38 UTC
It is very likely that YT will do something about it. Therefore, you could put a bit pattern over a normal video. Therefore, it is very difficult to detect this bit pattern without knowing the algorithm. The length of the video could then be adjusted dynamically. Of course, the overhead is significantly larger. But maybe it is possible to "overlay" several bit patterns. I would also find it exciting to automatically synchronize these videos with YT via a client.

**Comment by L1-0** [comment] 2023-02-23 17:19
Maybe this could be dealt with by choosing a random overlay video. Then either combine them with a transparency or sacrifice a video color channel that can be extracted again later.

**Comment by Friedjof** [comment] 2023-02-23 17:36
> Maybe this could be dealt with by choosing a random overlay video. Then either combine them with a transparency or sacrifice a video color channel that can be extracted again later.

You could change the color values a bit. If you use the smallest bit, the video will not change visibly. But I don't know if YT compresses the video before or changes something else. This would have to be investigated.

**Comment by DvorakDwarf** [comment] 2023-02-23 20:25
Duplicate of #7

**Closed by DvorakDwarf** 2023-02-23 20:25 UTC
