### ISSUE TITLE
Text file busy (os error 26) on Docker when downloading file.

### ISSUE THREAD

**Issue by Shyvadi** [DvorakDwarf/Infinite-Storage-Glitch#63] opened 2023-02-24 09:12 UTC
![image](https://user-images.githubusercontent.com/22157510/221138962-5d431b6a-9b68-4f93-b184-2c177d0482ce.png)

**Comment by DvorakDwarf** [comment] 2023-02-24 22:02
Duplicate of #62

**Closed by DvorakDwarf** 2023-02-24 22:02 UTC
