### ISSUE TITLE
Support Storing the Files as Audio

### ISSUE THREAD

**Issue by 53142** [DvorakDwarf/Infinite-Storage-Glitch#44] opened 2023-02-23 16:06 UTC
Supporting audio storage will increase the data that would be able to be stored. You should also be able to export encoded videos with encoded audio.

**Comment by benhexie** [comment] 2023-02-23 17:51
Bruhhhh!!.... You guys are thinking in 4K XD

**Comment by 53142** [comment] 2023-02-23 18:30
Whoops, didn't realize this is kind of a duplicate of https://github.com/DvorakDwarf/Infinite-Storage-Glitch/issues/20

**Comment by zeromero-dev** [comment] 2023-02-23 21:55
> 

Didn't realize too. Good you mentioned it.
Closing this as a duplicate of #20

**Closed by zeromero-dev** 2023-02-23 21:55 UTC
Labels: enhancement
