### ISSUE TITLE
need a color video to increase compression

### ISSUE THREAD

**Issue by OmlineEditor** [DvorakDwarf/Infinite-Storage-Glitch#11] opened 2023-02-21 17:32 UTC
there is not enough data in black and white video, color video is needed to increase compression. use only 16 colors so that it will be possible to accurately recognize them later when pinching

**Comment by danya02** [comment] 2023-02-21 19:10
I think this is a duplicate of #1.

**Comment by DvorakDwarf** [comment] 2023-02-21 23:45
Duplicate of #1

**Closed by DvorakDwarf** 2023-02-21 23:45 UTC
